#! /bin/sh
#
# copyfilesfromAD
#
# remove local AutoGrid versions of key source files shared with AutoDock,
#  replacing them with copies from ../autodock
# 
# option -r   : removes these files, does not copy 
#
# $Id: copyfilesfromAD,v 1.2 2012/10/24 23:40:27 mp Exp $
#
# M Pique

copy=y
if [ test$1 = test-r ]; then
  copy=n
fi

DO="ln -s"
DO="cp -p"

# .cpp and .h if present in ../autodock
for c in  \
	mingw_getrusage \
	mingw_sysconf \
	mingw_sys_times \
	parse_param_line \
	printhms \
	printdate \
	read_parameter_library \
	stop \
	timesys \
	timesyshms \
  ; do
   rm -f $c.cpp $c.h
   test $copy = y && test -r ../autodock/$c.cc && $DO  ../autodock/$c.cc $c.cpp
   test $copy = y && test -r ../autodock/$c.h && $DO  ../autodock/$c.h  $c.h
done

# other needed files

test $copy = y && test -r ../autodock/configure-universalDarwin \
 && $DO ../autodock/configure-universalDarwin configure-universalDarwin
