#! /bin/bash
# script to run AutoGrid automated tests (if "make" is not available)
# usage: (from source directory):  cd $ARCHOSV; ../makecheck
#
# $Id: makecheck,v 1.4 2015/10/14 06:28:18 mp Exp $
#
echo "Running the Python test_autogrid4.py unit-tests on ../autogrid4"
outputdir=`pwd` ;\
	umask 0 ;\
	test -d $outputdir/Tests || mkdir $outputdir/Tests ;\
    rm -f $outputdir/Tests/test_autogrid4.py;\
    cp ../Tests/AD4.1_bound.dat  $outputdir/Tests;\
    cp ../Tests/*.py   $outputdir/Tests;\
    cp ../Tests/*.gpf  $outputdir/Tests;\
    cp ../Tests/*.pdbqt  $outputdir/Tests;\
    cp -p ../Tests/*.map*  $outputdir/Tests;\
	cd $outputdir/Tests ;  python ./test_autogrid4.py -d . -e ../autogrid4 -o .
